// frontend/src/components/TraceList.vue
<template>
  <n-card title="Traces" :bordered="false">
    <n-space vertical>
      <n-data-table
        :key="tableKey"
        :columns="columns"
        :data="traces"
        :pagination="pagination"
        :loading="loading"
        :row-key="rowKey"
        :row-props="rowProps"
        remote
        @update:page="handlePageChange"
        @update:page-size="handlePageSizeChange"
      />
    </n-space>
  </n-card>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, h } from 'vue'
import { useRouter } from 'vue-router'
import { NCard, NDataTable, NSpace, NButton, NTag, useMessage } from 'naive-ui'
import type { DataTableColumns } from 'naive-ui'
import { apiService } from '@/services/api'

const router = useRouter()
const message = useMessage()

const loading = ref(false)
const traces = ref<any[]>([])
const totalTraces = ref(0)
const currentPage = ref(1)
const pageSize = ref(50)
const annotations = ref<Map<string, any>>(new Map())
const tableKey = ref(0)

const columns: DataTableColumns<any> = [
  {
    title: 'Status',
    key: 'status',
    width: 80,
    render(row) {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) {
        return h('span', { 'aria-label': 'Not annotated', style: { fontSize: '18px' } }, '○')
      }
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return h('span', {
          'aria-label': 'Pass',
          style: { fontSize: '18px', color: 'rgb(34, 197, 94)' }
        }, '✓')
      } else if (passFailStatus === 'Fail') {
        return h('span', {
          'aria-label': 'Fail',
          style: { fontSize: '18px', color: 'rgb(239, 68, 68)' }
        }, '✗')
      }
      return h('span', { 'aria-label': 'Unknown' }, '?')
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  },
  {
    title: 'Trace ID',
    key: 'trace_id',
    width: 180,
    ellipsis: {
      tooltip: true
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  },
  {
    title: 'Session',
    key: 'flow_session',
    width: 150,
    ellipsis: {
      tooltip: true
    },
    render(row) {
      return row.flow_session?.substring(0, 8) + '...'
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  },
  {
    title: 'Turn',
    key: 'turn_number',
    width: 80,
    render(row) {
      return `${row.turn_number}/${row.total_turns}`
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  },
  {
    title: 'User Message',
    key: 'user_message',
    ellipsis: {
      tooltip: true
    },
    render(row) {
      return row.user_message?.substring(0, 100) + (row.user_message?.length > 100 ? '...' : '')
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  },
  {
    title: 'AI Response',
    key: 'ai_response',
    ellipsis: {
      tooltip: true
    },
    render(row) {
      return row.ai_response?.substring(0, 100) + (row.ai_response?.length > 100 ? '...' : '')
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  },
  {
    title: 'Actions',
    key: 'actions',
    width: 100,
    render(row) {
      return h(
        NButton,
        {
          size: 'small',
          onClick: () => viewTrace(row.trace_id)
        },
        { default: () => 'View' }
      )
    },
    cellProps: (row: any) => {
      const annotation = annotations.value.get(row.trace_id)
      if (!annotation) return {}
      const passFailStatus = annotation.holistic_pass_fail
      if (passFailStatus === 'Pass') {
        return { style: { backgroundColor: 'rgba(34, 197, 94, 0.15)' } }
      } else if (passFailStatus === 'Fail') {
        return { style: { backgroundColor: 'rgba(239, 68, 68, 0.15)' } }
      }
      return {}
    }
  }
]

const pagination = computed(() => ({
  page: currentPage.value,
  pageSize: pageSize.value,
  itemCount: totalTraces.value,
  showSizePicker: true,
  pageSizes: [20, 50, 100]
}))

const rowKey = (row: any) => row.trace_id

const rowProps = (row: any) => {
  const annotation = annotations.value.get(row.trace_id)

  console.log(`Row ${row.trace_id}: annotation =`, annotation)

  if (!annotation) return {}

  const passFailStatus = annotation.holistic_pass_fail
  console.log(`Trace ${row.trace_id} has annotation with status: ${passFailStatus}`)

  if (passFailStatus === 'Pass') {
    return {
      style: {
        'background-color': 'rgba(34, 197, 94, 0.15)'
      }
    }
  } else if (passFailStatus === 'Fail') {
    return {
      style: {
        'background-color': 'rgba(239, 68, 68, 0.15)'
      }
    }
  }
  return {}
}

const fetchTraces = async () => {
  loading.value = true
  try {
    const response = await apiService.getTraces(currentPage.value, pageSize.value)
    traces.value = response.traces
    totalTraces.value = response.total

    // Fetch annotations for current page traces
    await fetchAnnotationsForTraces(response.traces)
  } catch (error: any) {
    message.error('Failed to load traces')
    console.error('Error fetching traces:', error)
  } finally {
    loading.value = false
  }
}

const fetchAnnotationsForTraces = async (traceList: any[]) => {
  try {
    console.log(`Fetching annotations for ${traceList.length} traces`)
    // Fetch annotations for each trace
    const annotationPromises = traceList.map(trace =>
      apiService.getAnnotationForTrace(trace.trace_id).catch(() => null)
    )
    const annotationResults = await Promise.all(annotationPromises)

    console.log('Annotation results:', annotationResults)

    // Update annotations map
    annotations.value.clear()
    annotationResults.forEach((annotation, index) => {
      if (annotation) {
        console.log(`Adding annotation for trace ${traceList[index].trace_id}:`, annotation)
        annotations.value.set(traceList[index].trace_id, annotation)
        // Also add annotation directly to trace object to trigger re-render
        traceList[index]._annotation = annotation
      }
    })

    console.log(`Annotations map now has ${annotations.value.size} entries`)

    // Force update the traces array to trigger re-render
    traces.value = [...traceList]
    // Increment table key to force complete re-render
    tableKey.value++
  } catch (error) {
    console.error('Error fetching annotations:', error)
  }
}

const handlePageChange = (page: number) => {
  currentPage.value = page
  fetchTraces()
}

const handlePageSizeChange = (size: number) => {
  pageSize.value = size
  currentPage.value = 1  // Reset to first page
  fetchTraces()
}

const viewTrace = (traceId: string) => {
  router.push(`/trace/${traceId}`)
}

// Expose refresh method for parent components
defineExpose({
  refresh: fetchTraces
})

onMounted(() => {
  fetchTraces()
})
</script>

// frontend/src/components/TraceList/TraceList.tsx
// TraceList Component - Paginated list of traces
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Button, Badge } from '@sendle/sds-ui';
import { useTraces } from '../../hooks/useTraces';
import { apiService } from '../../services/api';
import type { Trace, Annotation } from '../../types/api';
import './TraceList.scss';

export const TraceList: React.FC = () => {
  const navigate = useNavigate();
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(50);
  const [annotations, setAnnotations] = useState<Map<string, Annotation>>(new Map());

  const { traces, total, loading, error, refresh } = useTraces(page, pageSize);

  // Fetch annotations for current page traces
  useEffect(() => {
    if (traces && traces.length > 0) {
      fetchAnnotationsForTraces(traces);
    }
  }, [traces]);

  const fetchAnnotationsForTraces = async (traceList: Trace[]) => {
    try {
      const annotationPromises = traceList.map((trace) =>
        apiService.getAnnotationForTrace(trace.trace_id).catch(() => null)
      );
      const annotationResults = await Promise.all(annotationPromises);

      const newAnnotations = new Map<string, Annotation>();
      annotationResults.forEach((annotation, index) => {
        if (annotation) {
          newAnnotations.set(traceList[index].trace_id, annotation);
        }
      });

      setAnnotations(newAnnotations);
    } catch (err) {
      console.error('Error fetching annotations:', err);
    }
  };

  const getStatusIndicator = (traceId: string) => {
    const annotation = annotations.get(traceId);
    if (!annotation) {
      return <span className="trace-list__status-icon trace-list__status-icon--unannotated" aria-label="Unannotated">○</span>;
    }
    if (annotation.holistic_pass_fail === 'Pass') {
      return <span className="trace-list__status-icon trace-list__status-icon--pass" aria-label="Pass">✓</span>;
    }
    if (annotation.holistic_pass_fail === 'Fail') {
      return <span className="trace-list__status-icon trace-list__status-icon--fail" aria-label="Fail">✗</span>;
    }
    return <span className="trace-list__status-icon" aria-label="Unknown">?</span>;
  };

  const getRowClassName = (traceId: string) => {
    const annotation = annotations.get(traceId);
    if (!annotation) return 'trace-list__row';
    if (annotation.holistic_pass_fail === 'Pass') {
      return 'trace-list__row trace-list__row--pass';
    }
    if (annotation.holistic_pass_fail === 'Fail') {
      return 'trace-list__row trace-list__row--fail';
    }
    return 'trace-list__row';
  };

  const truncateText = (text: string, maxLength: number) => {
    if (text.length <= maxLength) return text;
    return text.substring(0, maxLength) + '...';
  };

  const handleViewTrace = (traceId: string) => {
    navigate(`/trace/${traceId}`);
  };

  const handlePageChange = (newPage: number) => {
    setPage(newPage);
  };

  const handlePageSizeChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setPageSize(Number(e.target.value));
    setPage(1); // Reset to first page
  };

  const totalPages = Math.ceil(total / pageSize);

  if (loading && traces.length === 0) {
    return (
      <div className="trace-list">
        <div className="trace-list__loading">
          <div className="trace-list__spinner"></div>
          <p>Loading traces...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="trace-list">
        <div className="trace-list__error">
          <p>⚠️ Failed to load traces</p>
          <p className="trace-list__error-message">{error.message}</p>
          <Button variant="primary" onClick={() => refresh()}>
            Retry
          </Button>
        </div>
      </div>
    );
  }

  return (
    <div className="trace-list">
      <div className="trace-list__header">
        <h2 className="trace-list__title">Traces</h2>
        <div className="trace-list__controls">
          <label htmlFor="page-size">
            Rows per page:
            <select
              id="page-size"
              value={pageSize}
              onChange={handlePageSizeChange}
              className="trace-list__page-size-select"
            >
              <option value={20}>20</option>
              <option value={50}>50</option>
              <option value={100}>100</option>
            </select>
          </label>
        </div>
      </div>

      <div className="trace-list__table-container">
        <table className="trace-list__table">
          <thead>
            <tr>
              <th className="trace-list__th--status">STATUS</th>
              <th className="trace-list__th--trace-id">TRACE ID</th>
              <th className="trace-list__th--session">SESSION</th>
              <th className="trace-list__th--turn">TURN</th>
              <th className="trace-list__th--user-message">USER MESSAGE</th>
              <th className="trace-list__th--ai-response">AI RESPONSE</th>
              <th className="trace-list__th--actions">ACTIONS</th>
            </tr>
          </thead>
          <tbody>
            {traces.length === 0 ? (
              <tr>
                <td colSpan={7} className="trace-list__empty">
                  No traces found
                </td>
              </tr>
            ) : (
              traces.map((trace) => (
                <tr key={trace.trace_id} className={getRowClassName(trace.trace_id)}>
                  <td className="trace-list__cell trace-list__cell--center">
                    {getStatusIndicator(trace.trace_id)}
                  </td>
                  <td className="trace-list__cell" title={trace.trace_id}>
                    {truncateText(trace.trace_id, 24)}
                  </td>
                  <td className="trace-list__cell" title={trace.flow_session}>
                    {trace.flow_session.substring(0, 8)}...
                  </td>
                  <td className="trace-list__cell trace-list__cell--center">
                    {trace.turn_number}
                  </td>
                  <td className="trace-list__cell" title={trace.user_message}>
                    {truncateText(trace.user_message, 100)}
                  </td>
                  <td className="trace-list__cell" title={trace.ai_response}>
                    {truncateText(trace.ai_response, 100)}
                  </td>
                  <td className="trace-list__cell trace-list__cell--center">
                    <Button
                      variant="secondary"
                      size="small"
                      onClick={() => handleViewTrace(trace.trace_id)}
                    >
                      View
                    </Button>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>

      {totalPages > 1 && (
        <div className="trace-list__pagination">
          <Button
            variant="secondary"
            onClick={() => handlePageChange(page - 1)}
            disabled={page === 1 || loading}
          >
            Previous
          </Button>

          <span className="trace-list__page-info">
            Page {page} of {totalPages} ({total} total)
          </span>

          <Button
            variant="secondary"
            onClick={() => handlePageChange(page + 1)}
            disabled={page === totalPages || loading}
          >
            Next
          </Button>
        </div>
      )}
    </div>
  );
};

export default TraceList;
