// frontend/src/views/ImportView.vue
<template>
  <CsvImporter @import-complete="handleImportComplete" />
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router'
import CsvImporter from '@/components/CsvImporter.vue'

const router = useRouter()

const handleImportComplete = () => {
  // Redirect to traces view after successful import
  setTimeout(() => {
    router.push('/traces')
  }, 2000)
}
</script>

// frontend/src/views/ImportView.tsx
// ImportView - CSV import page
import React from 'react';
import { useNavigate } from 'react-router-dom';
import CsvImporter from '../components/CsvImporter';

export const ImportView: React.FC = () => {
  const navigate = useNavigate();

  const handleImportComplete = () => {
    // Navigate to traces list after successful import
    setTimeout(() => {
      navigate('/traces');
    }, 2000);
  };

  return (
    <div className="import-view" style={{ padding: '2rem' }}>
      <CsvImporter onImportComplete={handleImportComplete} />
    </div>
  );
};

export default ImportView;
